const fs = require('fs');
const path = require('path');

const LOGO_DIR = '/home/sleepwalker/Github/plaid-api-test/test-app/src/assets/duplicate_inst_logos';
const OUTPUT = '/home/sleepwalker/Github/plaid-api-test/test-app/src/assets/logoMap.ts';

const files = fs.readdirSync(LOGO_DIR).filter(f => f.endsWith('.png'));

const imports = files.map((f, i) => {
    const varName = f.replace('.png', '').replace('ins_', 'logo_');
    return `import ${varName} from './duplicate_inst_logos/${f}';`;
}).join('\n');

const mapEntries = files.map(f => {
    const varName = f.replace('.png', '').replace('ins_', 'logo_');
    return `    '${f}': ${varName},`;
}).join('\n');

const content = `// Auto-generated by scripts/generate_logo_map.js
// Maps logo filenames to require() statements for React Native

${imports}

export const logoMap: Record<string, any> = {
${mapEntries}
};

export default logoMap;
`;

fs.writeFileSync(OUTPUT, content);
console.log(`Generated logoMap.ts with ${files.length} entries`);
