// Auto-generated by scripts/generate_logo_map.js
// Maps logo filenames to require() statements for React Native

import logo_100402 from './duplicate_inst_logos/ins_100402.png';
import logo_100735 from './duplicate_inst_logos/ins_100735.png';
import logo_100994 from './duplicate_inst_logos/ins_100994.png';
import logo_101864 from './duplicate_inst_logos/ins_101864.png';
import logo_102886 from './duplicate_inst_logos/ins_102886.png';
import logo_103019 from './duplicate_inst_logos/ins_103019.png';
import logo_103055 from './duplicate_inst_logos/ins_103055.png';
import logo_103449 from './duplicate_inst_logos/ins_103449.png';
import logo_103912 from './duplicate_inst_logos/ins_103912.png';
import logo_106113 from './duplicate_inst_logos/ins_106113.png';
import logo_106450 from './duplicate_inst_logos/ins_106450.png';
import logo_107360 from './duplicate_inst_logos/ins_107360.png';
import logo_107361 from './duplicate_inst_logos/ins_107361.png';
import logo_108011 from './duplicate_inst_logos/ins_108011.png';
import logo_109620 from './duplicate_inst_logos/ins_109620.png';
import logo_109640 from './duplicate_inst_logos/ins_109640.png';
import logo_109641 from './duplicate_inst_logos/ins_109641.png';
import logo_109643 from './duplicate_inst_logos/ins_109643.png';
import logo_109714 from './duplicate_inst_logos/ins_109714.png';
import logo_109788 from './duplicate_inst_logos/ins_109788.png';
import logo_109789 from './duplicate_inst_logos/ins_109789.png';
import logo_110003 from './duplicate_inst_logos/ins_110003.png';
import logo_110459 from './duplicate_inst_logos/ins_110459.png';
import logo_110517 from './duplicate_inst_logos/ins_110517.png';
import logo_110540 from './duplicate_inst_logos/ins_110540.png';
import logo_110548 from './duplicate_inst_logos/ins_110548.png';
import logo_110721 from './duplicate_inst_logos/ins_110721.png';
import logo_110764 from './duplicate_inst_logos/ins_110764.png';
import logo_110768 from './duplicate_inst_logos/ins_110768.png';
import logo_110770 from './duplicate_inst_logos/ins_110770.png';
import logo_110779 from './duplicate_inst_logos/ins_110779.png';
import logo_110780 from './duplicate_inst_logos/ins_110780.png';
import logo_110793 from './duplicate_inst_logos/ins_110793.png';
import logo_110817 from './duplicate_inst_logos/ins_110817.png';
import logo_110820 from './duplicate_inst_logos/ins_110820.png';
import logo_110824 from './duplicate_inst_logos/ins_110824.png';
import logo_110848 from './duplicate_inst_logos/ins_110848.png';
import logo_111040 from './duplicate_inst_logos/ins_111040.png';
import logo_111098 from './duplicate_inst_logos/ins_111098.png';
import logo_111167 from './duplicate_inst_logos/ins_111167.png';
import logo_111192 from './duplicate_inst_logos/ins_111192.png';
import logo_111225 from './duplicate_inst_logos/ins_111225.png';
import logo_111238 from './duplicate_inst_logos/ins_111238.png';
import logo_111241 from './duplicate_inst_logos/ins_111241.png';
import logo_111280 from './duplicate_inst_logos/ins_111280.png';
import logo_111290 from './duplicate_inst_logos/ins_111290.png';
import logo_111393 from './duplicate_inst_logos/ins_111393.png';
import logo_111456 from './duplicate_inst_logos/ins_111456.png';
import logo_111529 from './duplicate_inst_logos/ins_111529.png';
import logo_111533 from './duplicate_inst_logos/ins_111533.png';
import logo_111547 from './duplicate_inst_logos/ins_111547.png';
import logo_111586 from './duplicate_inst_logos/ins_111586.png';
import logo_111590 from './duplicate_inst_logos/ins_111590.png';
import logo_111619 from './duplicate_inst_logos/ins_111619.png';
import logo_111625 from './duplicate_inst_logos/ins_111625.png';
import logo_111675 from './duplicate_inst_logos/ins_111675.png';
import logo_111689 from './duplicate_inst_logos/ins_111689.png';
import logo_111698 from './duplicate_inst_logos/ins_111698.png';
import logo_111715 from './duplicate_inst_logos/ins_111715.png';
import logo_111725 from './duplicate_inst_logos/ins_111725.png';
import logo_111750 from './duplicate_inst_logos/ins_111750.png';
import logo_111798 from './duplicate_inst_logos/ins_111798.png';
import logo_111814 from './duplicate_inst_logos/ins_111814.png';
import logo_111833 from './duplicate_inst_logos/ins_111833.png';
import logo_111858 from './duplicate_inst_logos/ins_111858.png';
import logo_112834 from './duplicate_inst_logos/ins_112834.png';
import logo_113171 from './duplicate_inst_logos/ins_113171.png';
import logo_113381 from './duplicate_inst_logos/ins_113381.png';
import logo_113589 from './duplicate_inst_logos/ins_113589.png';
import logo_113745 from './duplicate_inst_logos/ins_113745.png';
import logo_113809 from './duplicate_inst_logos/ins_113809.png';
import logo_113844 from './duplicate_inst_logos/ins_113844.png';
import logo_113901 from './duplicate_inst_logos/ins_113901.png';
import logo_114029 from './duplicate_inst_logos/ins_114029.png';
import logo_114127 from './duplicate_inst_logos/ins_114127.png';
import logo_114141 from './duplicate_inst_logos/ins_114141.png';
import logo_114173 from './duplicate_inst_logos/ins_114173.png';
import logo_114192 from './duplicate_inst_logos/ins_114192.png';
import logo_114228 from './duplicate_inst_logos/ins_114228.png';
import logo_114295 from './duplicate_inst_logos/ins_114295.png';
import logo_114441 from './duplicate_inst_logos/ins_114441.png';
import logo_114449 from './duplicate_inst_logos/ins_114449.png';
import logo_114457 from './duplicate_inst_logos/ins_114457.png';
import logo_114473 from './duplicate_inst_logos/ins_114473.png';
import logo_114490 from './duplicate_inst_logos/ins_114490.png';
import logo_114503 from './duplicate_inst_logos/ins_114503.png';
import logo_114552 from './duplicate_inst_logos/ins_114552.png';
import logo_114556 from './duplicate_inst_logos/ins_114556.png';
import logo_114581 from './duplicate_inst_logos/ins_114581.png';
import logo_114587 from './duplicate_inst_logos/ins_114587.png';
import logo_114614 from './duplicate_inst_logos/ins_114614.png';
import logo_114627 from './duplicate_inst_logos/ins_114627.png';
import logo_114644 from './duplicate_inst_logos/ins_114644.png';
import logo_114865 from './duplicate_inst_logos/ins_114865.png';
import logo_115359 from './duplicate_inst_logos/ins_115359.png';
import logo_115396 from './duplicate_inst_logos/ins_115396.png';
import logo_115414 from './duplicate_inst_logos/ins_115414.png';
import logo_115450 from './duplicate_inst_logos/ins_115450.png';
import logo_115470 from './duplicate_inst_logos/ins_115470.png';
import logo_115511 from './duplicate_inst_logos/ins_115511.png';
import logo_115563 from './duplicate_inst_logos/ins_115563.png';
import logo_116364 from './duplicate_inst_logos/ins_116364.png';
import logo_116448 from './duplicate_inst_logos/ins_116448.png';
import logo_116485 from './duplicate_inst_logos/ins_116485.png';
import logo_116707 from './duplicate_inst_logos/ins_116707.png';
import logo_116736 from './duplicate_inst_logos/ins_116736.png';
import logo_116931 from './duplicate_inst_logos/ins_116931.png';
import logo_117050 from './duplicate_inst_logos/ins_117050.png';
import logo_117091 from './duplicate_inst_logos/ins_117091.png';
import logo_117118 from './duplicate_inst_logos/ins_117118.png';
import logo_117261 from './duplicate_inst_logos/ins_117261.png';
import logo_117296 from './duplicate_inst_logos/ins_117296.png';
import logo_117325 from './duplicate_inst_logos/ins_117325.png';
import logo_117418 from './duplicate_inst_logos/ins_117418.png';
import logo_120003 from './duplicate_inst_logos/ins_120003.png';
import logo_120115 from './duplicate_inst_logos/ins_120115.png';
import logo_120122 from './duplicate_inst_logos/ins_120122.png';
import logo_120574 from './duplicate_inst_logos/ins_120574.png';
import logo_122776 from './duplicate_inst_logos/ins_122776.png';
import logo_123130 from './duplicate_inst_logos/ins_123130.png';
import logo_127195 from './duplicate_inst_logos/ins_127195.png';
import logo_127334 from './duplicate_inst_logos/ins_127334.png';
import logo_128264 from './duplicate_inst_logos/ins_128264.png';
import logo_129293 from './duplicate_inst_logos/ins_129293.png';
import logo_129294 from './duplicate_inst_logos/ins_129294.png';
import logo_130978 from './duplicate_inst_logos/ins_130978.png';
import logo_131833 from './duplicate_inst_logos/ins_131833.png';
import logo_131843 from './duplicate_inst_logos/ins_131843.png';
import logo_131844 from './duplicate_inst_logos/ins_131844.png';
import logo_131845 from './duplicate_inst_logos/ins_131845.png';
import logo_132008 from './duplicate_inst_logos/ins_132008.png';
import logo_132040 from './duplicate_inst_logos/ins_132040.png';
import logo_132041 from './duplicate_inst_logos/ins_132041.png';
import logo_132057 from './duplicate_inst_logos/ins_132057.png';
import logo_132171 from './duplicate_inst_logos/ins_132171.png';
import logo_132174 from './duplicate_inst_logos/ins_132174.png';
import logo_132408 from './duplicate_inst_logos/ins_132408.png';
import logo_132615 from './duplicate_inst_logos/ins_132615.png';
import logo_133283 from './duplicate_inst_logos/ins_133283.png';
import logo_133468 from './duplicate_inst_logos/ins_133468.png';
import logo_133892 from './duplicate_inst_logos/ins_133892.png';
import logo_134063 from './duplicate_inst_logos/ins_134063.png';
import logo_137391 from './duplicate_inst_logos/ins_137391.png';
import logo_137824 from './duplicate_inst_logos/ins_137824.png';
import logo_137938 from './duplicate_inst_logos/ins_137938.png';
import logo_138066 from './duplicate_inst_logos/ins_138066.png';
import logo_138079 from './duplicate_inst_logos/ins_138079.png';
import logo_138253 from './duplicate_inst_logos/ins_138253.png';
import logo_138462 from './duplicate_inst_logos/ins_138462.png';
import logo_138780 from './duplicate_inst_logos/ins_138780.png';
import logo_138892 from './duplicate_inst_logos/ins_138892.png';
import logo_20 from './duplicate_inst_logos/ins_20.png';

export const logoMap: Record<string, any> = {
    'ins_100402.png': logo_100402,
    'ins_100735.png': logo_100735,
    'ins_100994.png': logo_100994,
    'ins_101864.png': logo_101864,
    'ins_102886.png': logo_102886,
    'ins_103019.png': logo_103019,
    'ins_103055.png': logo_103055,
    'ins_103449.png': logo_103449,
    'ins_103912.png': logo_103912,
    'ins_106113.png': logo_106113,
    'ins_106450.png': logo_106450,
    'ins_107360.png': logo_107360,
    'ins_107361.png': logo_107361,
    'ins_108011.png': logo_108011,
    'ins_109620.png': logo_109620,
    'ins_109640.png': logo_109640,
    'ins_109641.png': logo_109641,
    'ins_109643.png': logo_109643,
    'ins_109714.png': logo_109714,
    'ins_109788.png': logo_109788,
    'ins_109789.png': logo_109789,
    'ins_110003.png': logo_110003,
    'ins_110459.png': logo_110459,
    'ins_110517.png': logo_110517,
    'ins_110540.png': logo_110540,
    'ins_110548.png': logo_110548,
    'ins_110721.png': logo_110721,
    'ins_110764.png': logo_110764,
    'ins_110768.png': logo_110768,
    'ins_110770.png': logo_110770,
    'ins_110779.png': logo_110779,
    'ins_110780.png': logo_110780,
    'ins_110793.png': logo_110793,
    'ins_110817.png': logo_110817,
    'ins_110820.png': logo_110820,
    'ins_110824.png': logo_110824,
    'ins_110848.png': logo_110848,
    'ins_111040.png': logo_111040,
    'ins_111098.png': logo_111098,
    'ins_111167.png': logo_111167,
    'ins_111192.png': logo_111192,
    'ins_111225.png': logo_111225,
    'ins_111238.png': logo_111238,
    'ins_111241.png': logo_111241,
    'ins_111280.png': logo_111280,
    'ins_111290.png': logo_111290,
    'ins_111393.png': logo_111393,
    'ins_111456.png': logo_111456,
    'ins_111529.png': logo_111529,
    'ins_111533.png': logo_111533,
    'ins_111547.png': logo_111547,
    'ins_111586.png': logo_111586,
    'ins_111590.png': logo_111590,
    'ins_111619.png': logo_111619,
    'ins_111625.png': logo_111625,
    'ins_111675.png': logo_111675,
    'ins_111689.png': logo_111689,
    'ins_111698.png': logo_111698,
    'ins_111715.png': logo_111715,
    'ins_111725.png': logo_111725,
    'ins_111750.png': logo_111750,
    'ins_111798.png': logo_111798,
    'ins_111814.png': logo_111814,
    'ins_111833.png': logo_111833,
    'ins_111858.png': logo_111858,
    'ins_112834.png': logo_112834,
    'ins_113171.png': logo_113171,
    'ins_113381.png': logo_113381,
    'ins_113589.png': logo_113589,
    'ins_113745.png': logo_113745,
    'ins_113809.png': logo_113809,
    'ins_113844.png': logo_113844,
    'ins_113901.png': logo_113901,
    'ins_114029.png': logo_114029,
    'ins_114127.png': logo_114127,
    'ins_114141.png': logo_114141,
    'ins_114173.png': logo_114173,
    'ins_114192.png': logo_114192,
    'ins_114228.png': logo_114228,
    'ins_114295.png': logo_114295,
    'ins_114441.png': logo_114441,
    'ins_114449.png': logo_114449,
    'ins_114457.png': logo_114457,
    'ins_114473.png': logo_114473,
    'ins_114490.png': logo_114490,
    'ins_114503.png': logo_114503,
    'ins_114552.png': logo_114552,
    'ins_114556.png': logo_114556,
    'ins_114581.png': logo_114581,
    'ins_114587.png': logo_114587,
    'ins_114614.png': logo_114614,
    'ins_114627.png': logo_114627,
    'ins_114644.png': logo_114644,
    'ins_114865.png': logo_114865,
    'ins_115359.png': logo_115359,
    'ins_115396.png': logo_115396,
    'ins_115414.png': logo_115414,
    'ins_115450.png': logo_115450,
    'ins_115470.png': logo_115470,
    'ins_115511.png': logo_115511,
    'ins_115563.png': logo_115563,
    'ins_116364.png': logo_116364,
    'ins_116448.png': logo_116448,
    'ins_116485.png': logo_116485,
    'ins_116707.png': logo_116707,
    'ins_116736.png': logo_116736,
    'ins_116931.png': logo_116931,
    'ins_117050.png': logo_117050,
    'ins_117091.png': logo_117091,
    'ins_117118.png': logo_117118,
    'ins_117261.png': logo_117261,
    'ins_117296.png': logo_117296,
    'ins_117325.png': logo_117325,
    'ins_117418.png': logo_117418,
    'ins_120003.png': logo_120003,
    'ins_120115.png': logo_120115,
    'ins_120122.png': logo_120122,
    'ins_120574.png': logo_120574,
    'ins_122776.png': logo_122776,
    'ins_123130.png': logo_123130,
    'ins_127195.png': logo_127195,
    'ins_127334.png': logo_127334,
    'ins_128264.png': logo_128264,
    'ins_129293.png': logo_129293,
    'ins_129294.png': logo_129294,
    'ins_130978.png': logo_130978,
    'ins_131833.png': logo_131833,
    'ins_131843.png': logo_131843,
    'ins_131844.png': logo_131844,
    'ins_131845.png': logo_131845,
    'ins_132008.png': logo_132008,
    'ins_132040.png': logo_132040,
    'ins_132041.png': logo_132041,
    'ins_132057.png': logo_132057,
    'ins_132171.png': logo_132171,
    'ins_132174.png': logo_132174,
    'ins_132408.png': logo_132408,
    'ins_132615.png': logo_132615,
    'ins_133283.png': logo_133283,
    'ins_133468.png': logo_133468,
    'ins_133892.png': logo_133892,
    'ins_134063.png': logo_134063,
    'ins_137391.png': logo_137391,
    'ins_137824.png': logo_137824,
    'ins_137938.png': logo_137938,
    'ins_138066.png': logo_138066,
    'ins_138079.png': logo_138079,
    'ins_138253.png': logo_138253,
    'ins_138462.png': logo_138462,
    'ins_138780.png': logo_138780,
    'ins_138892.png': logo_138892,
    'ins_20.png': logo_20,
};

export default logoMap;
