const SUBTYPES_BY_TYPE = {
    depository: [
        'cash management',
        'cd',
        'checking',
        'ebt',
        'hsa',
        'limited purpose checking',
        'money market',
        'paypal',
        'prepaid',
        'savings',
    ],
    credit: [
        'credit card',
        'paypal',
    ],
    loan: [
        'auto',
        'business',
        'commercial',
        'construction',
        'consumer',
        'home equity',
        'line of credit',
        'loan',
        'mortgage',
        'other',
        'overdraft',
        'student',
    ],
    investment: [
        '529',
        '401a',
        '401k',
        '403B',
        '457b',
        'brokerage',
        'cash isa',
        'crypto exchange',
        'education savings account',
        'fhsa',
        'fixed annuity',
        'gic',
        'health reimbursement arrangement',
        'hsa',
        'ira',
        'isa',
        'keogh',
        'lif',
        'life insurance',
        'lira',
        'lrif',
        'lrsp',
        'mutual fund',
        'non-custodial wallet',
        'non-taxable brokerage account',
        'other',
        'other annuity',
        'other insurance',
        'pension',
        'prediction market',
        'prif',
        'profit sharing plan',
        'qshr',
        'rdsp',
        'resp',
        'retirement',
        'rlif',
        'roth',
        'roth401k',
        'roth403B',
        'roth457b',
        'roth pension',
        'roth profit sharing plan',
        'roth thrift savings plan',
        'rrif',
        'rrsp',
        'sarsep',
        'sep ira',
        'simple ira',
        'sipp',
        'stock plan',
        'tfsa',
        'thrift savings plan',
        'trust',
        'ugma',
        'utma',
        'variable annuity',
    ],
    payroll: [
        'payroll',
    ],
    other: ['other'],
};

function isValidPlaidAccountType(type, subtype) {
    return type in SUBTYPES_BY_TYPE
        && (
            subtype === null
            || subtype === 'other'
            || SUBTYPES_BY_TYPE[type].includes(subtype)
        )
}

module.exports = {
    SUBTYPES_BY_TYPE,
    isValidPlaidAccountType,
};
